In [88]:
#hey
# Numpy(numericalpython) is pythonic version of a matlab numerical libraries
#can create matrix , arrays,multidimensional metrices..watever dataframe we have , we can convert it in to metrices
#numpy is special library
#dataframe is always 2 dimension

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,4]

In [4]:
type(l)

list

In [5]:
a = np.array(l)

In [6]:
a

array([1, 2, 3, 4, 4])

In [7]:
type(a)

numpy.ndarray

In [8]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [9]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[[1,2,3] , [4,.5,6]]])

In [12]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [13]:
a

array([1, 2, 3, 4, 4])

In [14]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [16]:
a.ndim

1

In [18]:
a1.ndim

2

In [19]:
a2.ndim

3

In [20]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [21]:
type(a3)

numpy.ndarray

In [22]:
a3.ndim

3

In [24]:
#3D is combination of 2D
#2D is combination of 1D

In [25]:

l = [1,2,3,4]

In [30]:
a = np.asarray(l)#array will have 0 o 1 dimension

In [31]:
m = np.matrix(l) #matrix is going to be minimum of 2 dimension ...atleast it will have 2 dimension

In [32]:
a

array([1, 2, 3, 4])

In [33]:
m

matrix([[1, 2, 3, 4]])

In [34]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [35]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [36]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [37]:
a

array([1, 2, 3, 4])

In [38]:
a1=a

In [39]:
a1

array([1, 2, 3, 4])

In [40]:
a

array([1, 2, 3, 4])

In [41]:
a[0]

1

In [42]:
a[1]

2

In [43]:
a[0]=10

In [44]:
a # 1 has change to 10

array([10,  2,  3,  4])

In [45]:
a1

array([10,  2,  3,  4])

In [58]:
a1[3]=50 #shallow copy

# 

In [57]:
a1 #shallow copy

array([10,  3,  3, 50])

In [56]:
a #shallow copy

array([10,  3,  3, 50])

In [55]:
a2=np.copy(a)#deep copy

In [51]:
a2

array([10,  3,  3, 50])

In [52]:
a2[2]=30

In [53]:
a2

array([10,  3, 30, 50])

In [54]:
a #it  dint reflect ..3 is same as it is

array([10,  3,  3, 50])

In [59]:
np.fromfunction(lambda i,j : i==j , (3,4)) #it generated 2 Dimensional aray ,,,, 3 row 4 column  

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [60]:
np.fromfunction(lambda i,j: i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [61]:
#numpy is used to generate data 

In [64]:
np.random.rand(2,3,2)  # 2 matrix will generate , 3 rows 2 columns

array([[[0.66373066, 0.96189223],
        [0.27354811, 0.13369454],
        [0.07772634, 0.84241349]],

       [[0.16827714, 0.22339331],
        [0.74383322, 0.91403275],
        [0.11294417, 0.59024851]]])

In [65]:
np.random.rand(2,3)

array([[0.80950603, 0.89342628, 0.55891375],
       [0.60519526, 0.20938889, 0.3106479 ]])

In [66]:
np.random.rand(2,3,2,2)

array([[[[0.9316529 , 0.0441985 ],
         [0.337446  , 0.98105611]],

        [[0.40471995, 0.20269273],
         [0.66814931, 0.26751299]],

        [[0.11545334, 0.84207564],
         [0.82042579, 0.86696533]]],


       [[[0.61929622, 0.62527039],
         [0.67616748, 0.75657243]],

        [[0.06281251, 0.61404287],
         [0.41544014, 0.80620945]],

        [[0.36735527, 0.19036313],
         [0.39974631, 0.13936754]]]])

In [67]:
np.random.rand(3,4,5)

array([[[0.6125717 , 0.00228354, 0.33066973, 0.776437  , 0.23129894],
        [0.26075741, 0.58863518, 0.07876633, 0.3592854 , 0.83491246],
        [0.04218555, 0.84862481, 0.80487483, 0.25964129, 0.65208844],
        [0.82384812, 0.35322666, 0.9234598 , 0.95659292, 0.99330869]],

       [[0.80105488, 0.14573696, 0.38662886, 0.86794026, 0.32271884],
        [0.68922712, 0.29165775, 0.72432171, 0.43555283, 0.84364347],
        [0.6282933 , 0.24078705, 0.03940275, 0.56219943, 0.16469072],
        [0.00780766, 0.56493402, 0.25566596, 0.55019227, 0.89438143]],

       [[0.44633309, 0.53151062, 0.26517238, 0.20879134, 0.24804401],
        [0.13460111, 0.85219787, 0.66186828, 0.36332338, 0.33690172],
        [0.50986697, 0.0748556 , 0.23706782, 0.30674011, 0.68170538],
        [0.46922032, 0.1290316 , 0.73300913, 0.14378557, 0.83506247]]])

In [68]:
d = np.random.randn(3,4) #it will generate standard normal distribution ( its mean is 0, standard deviation =1)

In [75]:
d

array([[ 0.33032132,  1.30007753, -0.55863162, -0.28563819],
       [ 2.04596262, -0.97099108, -1.37245803,  0.4401074 ],
       [ 1.54948992, -0.24776372,  0.40199743,  0.40546974]])

In [78]:
import pandas as pd
pd.DataFrame(d)

0         1         2         3
0  0.330321  1.300078 -0.558632 -0.285638
1  2.045963 -0.970991 -1.372458  0.440107
2  1.549490 -0.247764  0.401997  0.405470

In [72]:
d1=np.random.randint(0,10,(4,4,2)) #generate random numbers from 0 to 10 , and 4 matrix, 4 rows and 2 columns

In [73]:
d1

array([[[8, 2],
        [9, 7],
        [8, 6],
        [1, 8]],

       [[7, 2],
        [3, 2],
        [2, 1],
        [1, 1]],

       [[1, 0],
        [1, 0],
        [3, 0],
        [0, 1]],

       [[6, 8],
        [0, 6],
        [0, 6],
        [7, 3]]])

In [81]:
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [82]:
d1.reshape(16,2)  #(4,4,2)  4*4 =16*2 =32 ...32 should be result to give for reshape 

array([[8, 2],
       [9, 7],
       [8, 6],
       [1, 8],
       [7, 2],
       [3, 2],
       [2, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [3, 0],
       [0, 1],
       [6, 8],
       [0, 6],
       [0, 6],
       [7, 3]])

In [83]:
d1.reshape(8,2) # see cannot reshape bcoz 8*2 =16 not 32 ..

ValueError: cannot reshape array of size 32 into shape (8,2)

In [84]:
d1.reshape(8,4)

array([[8, 2, 9, 7],
       [8, 6, 1, 8],
       [7, 2, 3, 2],
       [2, 1, 1, 1],
       [1, 0, 1, 0],
       [3, 0, 0, 1],
       [6, 8, 0, 6],
       [0, 6, 7, 3]])

In [85]:
d1.reshape(8,-1)# if u give any negative number also it will reshape

array([[8, 2, 9, 7],
       [8, 6, 1, 8],
       [7, 2, 3, 2],
       [2, 1, 1, 1],
       [1, 0, 1, 0],
       [3, 0, 0, 1],
       [6, 8, 0, 6],
       [0, 6, 7, 3]])

In [86]:
d1.reshape(16,-18907)

array([[8, 2],
       [9, 7],
       [8, 6],
       [1, 8],
       [7, 2],
       [3, 2],
       [2, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [3, 0],
       [0, 1],
       [6, 8],
       [0, 6],
       [0, 6],
       [7, 3]])

In [87]:
pd.DataFrame(d1.reshape(32,-1987987))

0
0   8
1   2
2   9
3   7
4   8
5   6
6   1
7   8
8   7
9   2
10  3
11  2
12  2
13  1
14  1
15  1
16  1
17  0
18  1
19  0
20  3
21  0
22  0
23  1
24  6
25  8
26  0
27  6
28  0
29  6
30  7
31  3