In [ ]:
#Range function is generator function
#yield function is to create generator function 

In [2]:
import numpy as np

In [3]:
range(10)

range(0, 10)

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(3 ,10))

[3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(3 ,10.5))#float cannot be interpreted

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(.5 , 10) #numpy using arange function can be generated float object

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [11]:
np.arange(5 ,-4, -1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [12]:
np.arange(5 ,-4, -.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [15]:
np.linspace(1,5,10) #in the range 1 to 5 , it will give u 10 dataset

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
list(np.linspace(1,5,20,retstep=True)) #it will give junk size

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [16]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((3,5,2)) #it will 5 rows 2 columns and 3 matrices

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
np.ones((3,4,2)) *5 

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [23]:
np.ones((3,4,2)) +5 

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [29]:
np.empty((2,3))

array([[1.51839631e-311, 1.51839631e-311, 1.51839631e-311],
       [1.51839631e-311, 1.51839631e-311, 1.51839631e-311]])

In [30]:
np.eye(4) #it will generate 4 cross 4 metrices

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
a=np.eye(4)

In [32]:
a.shape

(4, 4)

In [33]:
a.size

16

In [34]:
a.ndim

2

In [35]:
a1 = np.random.randn(3,4)

In [36]:
a1 #if i want 0.2757982, how to extract ? ,to use iloc ,we need to make data in dataframe 

array([[ 0.70291708, -1.47860186,  0.52635461,  0.54973502],
       [-0.92860265,  0.27537982, -0.12040908, -0.91975758],
       [ 0.21981496, -0.10634504,  0.03387305, -0.96838236]])

In [38]:
import pandas as pd
pd.DataFrame(a1)

0         1         2         3
0  0.702917 -1.478602  0.526355  0.549735
1 -0.928603  0.275380 -0.120409 -0.919758
2  0.219815 -0.106345  0.033873 -0.968382

In [39]:
a1

array([[ 0.70291708, -1.47860186,  0.52635461,  0.54973502],
       [-0.92860265,  0.27537982, -0.12040908, -0.91975758],
       [ 0.21981496, -0.10634504,  0.03387305, -0.96838236]])

In [40]:
a1[1][1] #this is how , you can extract the number

0.2753798159597032

In [41]:
a1[0:2 , 0:2] #0:2 is 0 to 1 is from rows and 0:2 is 0 to 1 from columns

array([[ 0.70291708, -1.47860186],
       [-0.92860265,  0.27537982]])

In [42]:
a1[[0,1] , 0:2]

array([[ 0.70291708, -1.47860186],
       [-0.92860265,  0.27537982]])

In [43]:
a1[[0,1] ,0:2]

array([[ 0.70291708, -1.47860186],
       [-0.92860265,  0.27537982]])

In [44]:
a1

array([[ 0.70291708, -1.47860186,  0.52635461,  0.54973502],
       [-0.92860265,  0.27537982, -0.12040908, -0.91975758],
       [ 0.21981496, -0.10634504,  0.03387305, -0.96838236]])

In [47]:
a1[[1,2],3] #1,2 is row and 3 is column ... we are extractiing data from a1 ... -0.91975758 and-0.968382

array([-0.91975758, -0.96838236])

In [48]:
m1 = np.random.randint(1,3 , (3,3))

In [49]:
m2 = np.random.randint(2,4 , (3,3))

In [50]:
m1

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [51]:
m2

array([[2, 2, 2],
       [2, 2, 3],
       [2, 3, 2]])

In [52]:
m1*m2 #it is element wise multiplication , it is not metrix multiplication 

array([[2, 4, 2],
       [2, 4, 6],
       [2, 3, 4]])

In [53]:
m1@m2 #this is metrix multiplication

array([[ 8,  9, 10],
       [10, 12, 12],
       [ 8, 10,  9]])

In [54]:
pow(m1 , 4) #pow is power ... power of 4 in m1 

array([[ 1, 16,  1],
       [ 1, 16, 16],
       [ 1,  1, 16]], dtype=int32)

In [55]:
np.sqrt(m1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [56]:
np.log10(m1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.     , 0.     , 0.30103]])

In [57]:
np.exp(m1) #exponential

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [58]:
m1**2 #m1 to the power of 2 .. you can use pow function

array([[1, 4, 1],
       [1, 4, 4],
       [1, 1, 4]])